// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VwP5rWBg2Udyk-ZYPnI8D7YiHyuybFk',
    appId: '1:926866745271:web:7fd51188af45222b03ea32',
    messagingSenderId: '926866745271',
    projectId: 'menu-platform-a4a27',
    authDomain: 'menu-platform-a4a27.firebaseapp.com',
    storageBucket: 'menu-platform-a4a27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWPZEbpJjkrUSJUu93Uv3vEDKal5zBuA',
    appId: '1:926866745271:android:d629490f4cf0c3ca03ea32',
    messagingSenderId: '926866745271',
    projectId: 'menu-platform-a4a27',
    storageBucket: 'menu-platform-a4a27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwo6611c4Wu12ib3xc_lRjVhHcUmW8xE',
    appId: '1:926866745271:ios:4b7b7682a2ad04fe03ea32',
    messagingSenderId: '926866745271',
    projectId: 'menu-platform-a4a27',
    storageBucket: 'menu-platform-a4a27.appspot.com',
    iosBundleId: 'com.example.digitalMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwo6611c4Wu12ib3xc_lRjVhHcUmW8xE',
    appId: '1:926866745271:ios:4b7b7682a2ad04fe03ea32',
    messagingSenderId: '926866745271',
    projectId: 'menu-platform-a4a27',
    storageBucket: 'menu-platform-a4a27.appspot.com',
    iosBundleId: 'com.example.digitalMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1VwP5rWBg2Udyk-ZYPnI8D7YiHyuybFk',
    appId: '1:926866745271:web:199f6faf7cf80cf203ea32',
    messagingSenderId: '926866745271',
    projectId: 'menu-platform-a4a27',
    authDomain: 'menu-platform-a4a27.firebaseapp.com',
    storageBucket: 'menu-platform-a4a27.appspot.com',
  );

}